sudo: required
services:
  - docker

before_install:
  - docker build -t magom001/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run magom001/react-test npm run test:nowatch

after_success:
  - docker build -t magom001/github-docker-travis-workflow-client ./client
  - docker build -t magom001/github-docker-travis-workflow-nginx ./nginx
  - docker build -t magom001/github-docker-travis-workflow-server ./server
  - docker build -t magom001/github-docker-travis-workflow-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push magom001/github-docker-travis-workflow-client
  - docker push magom001/github-docker-travis-workflow-nginx
  - docker push magom001/github-docker-travis-workflow-server
  - docker push magom001/github-docker-travis-workflow-worker
